# Generated by Django 3.0.2 on 2020-01-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pagetype', models.SmallIntegerField(choices=[(1, 'news'), (2, 'event')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20)),
                ('html_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
