# Generated by Django 3.0.2 on 2020-01-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0002_historicalstaticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstaticpage',
            name='pagetype',
            field=models.SmallIntegerField(choices=[(1, 'top'), (2, 'eventContents'), (3, 'supporter')]),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='pagetype',
            field=models.SmallIntegerField(choices=[(1, 'top'), (2, 'eventContents'), (3, 'supporter')]),
        ),
    ]
